### ISSUE TITLE
Rebuild docker-compose projects on re-deployment

### ISSUE THREAD

**Issue by benmerckx** [exoframejs/exoframe#108]
Redeploying projects using docker-compose results in a `docker-compose up -d`, but this does not rebuild images when needed (the web service is only built once):

````
version: '2'
services:
  web:
    build: '.'
    labels:
      traefik.frontend.rule: 'Host:...'
````
Can we have a way to run `docker-compose build` on deploy? Or is there something I'm missing?
