### ISSUE TITLE
Supply Traefik config file

### ISSUE THREAD

**Issue by Harjot1Singh** [exoframejs/exoframe#139]
Hi, great work!

I noticed that it’s possible to add command line arguments to Traefik within the config, however this can be cumbersome with more than a handful of options.

Is there a way of supplying Traefik with the path of a configuration file?

**Comment by yamalight** [comment]
Hi @Harjot1Singh!

There's no current way to do that, but I'd be open to a PR for that.
It's going to be a bit tricky to implement because you need to provide pretty flexible core (see [this code for reference](https://github.com/exoframejs/exoframe-server/blob/master/src/docker/init.js#L130)).

**Comment by anbraten** [comment]
Traefik isn't merging cli options with settings from a config file. [check traefik docs](https://docs.traefik.io/v2.0/getting-started/configuration-overview/#the-static-configuration) 

To provide the ability to supply a custom traefik config file we would need to add exoframe specific settings to the provided config file.

Maybe we could create a sample toml config after starting the server in `/root/.exoframe/traefik/traefik.toml` and add the whole exoframe specific config to the beginning by using [toml](https://www.npmjs.com/package/toml). Adding an option to disable the config generation at all should also be available.

The file could look like this:
``` toml
# Dynamic config file for Traefik. This upper part is generated by exoframe. 
# Please add your own changes to the bottom of the file.
# DO NOT EDIT THIS PART BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
[log]
  level = "warning"

[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

[certificatesResolvers]
  [certificatesResolvers.httpchallenge]
    [certificatesResolvers.httpchallenge.acme]
      storage = "/etc/traefik/acme/acme.json"
      [certificatesResolvers.httpchallenge.acme.httpChallenge]
        entryPoint = "web"

### add you custom config below this line
[api]
  dashboard = true
```
