### ISSUE TITLE
Document manual docker-compose labels usage

### ISSUE THREAD

**Issue by FrosmoPerfetta** [exoframejs/exoframe#171]
Having a following docker-compose.yml:
```
version: "3.3"
services:
  web:
    build: .
    environment:
      DB_1_PORT_27017_TCP_ADDR: mongo
      PORT: 80
      NODE_ENV: production
    depends_on:
      - mongo
    expose:
      - "80"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always
```

and the following exoframe.json:

```
{
  "name": "acme-app",
  "restart": "always",
  "domain": "acme.example.com",
}
```

This app still is not available as acme.example.com with traefik.
Even setting labels doesn't help:
```
"labels":{ "traefik.frontend.rule": "Host:acme.example.com" }
```

**Comment by FrosmoPerfetta** [comment]
Well, could you then please help me solve my task @yamalight ?
I need an app to be deployed on a dynamic domain depending on the branch name.
Like `master.acme.example.com` for master.
I could pass this `master` name as an env variable `DOMAIN` to docker-comose and write there something like `traefik.frontend.rule: "Host:${DOMAIN}.acme.example.com"`, but this doesn't work either. 
Env variable is not pass neither when setting it for `exoframe` call nor setting in exoframe.json in `env` section.

**Comment by yamalight** [comment]
here's how you `docker-compose.yml` should look:
```yml
version: "3.3"
services:
  web:
    build: .
    environment:
      DB_1_PORT_27017_TCP_ADDR: mongo
      PORT: 80
      NODE_ENV: production
    labels:
      traefik.frontend.rule: "Host:master.acme.example.com"
      traefik.port: 80
    depends_on:
      - mongo
    expose:
      - "80"
  mongo:
    container_name: mongo
    image: mongo
    restart: always
```
