### ISSUE TITLE
Docker-compose with named volumes results in phantom error

### ISSUE THREAD

**Issue by JoeLanglois** [exoframejs/exoframe#181]
Here is my docker-compose.yml file:
```
version: '2'
services:
  web:
    env_file: config/prod.env
    volumes:
      - dbdata:/usr/src/app/data
    build: .
    labels:
      traefik.frontend.rule: 'Host:xxx.xx.com'
      traefik.frontend.entryPoints: 'http,https'
volumes:
    -dbdata:
```

The volume dbdata is already created on the host.
When I try to exoframe -u or exoframe...

I get:
```
✖ Deployment failed!
Error deploying project: Error: Something went wrong!
Build log:

No log available
```

And this only happens when I add the volumes sections to the docker-compose file. Otherwise, everything works fine.

Any idea why? Or how to debug that?
