### ISSUE TITLE
Possibility to build locally

### ISSUE THREAD

**Issue by mradke** [exoframejs/exoframe#207]
I hope opening an issue for this is appropriate.

**What I'd like to do**
Deploy a bundle / binary that was built locally

**What I think exoframe is doing**
Building the bundle on the server (or don't bundle at all) and run that.

**Why would I like to do that?**
My build process is pretty slow and expensive and I certainly don't want to do that on my production machine (especially not when it is an underpowered VPS 😁 ). So I'd like to do that either locally or on a build server.

**Questions**
- Does that sound reasonable and/or do you need more info?
- Maybe it is already possible?

Thank you 🙂

**Comment by yamalight** [comment]
Opening an issue is totally fine :)

Currently, it's not possible directly with exoframe, but this is something I want to have in the nearest future.
There's a relevant issue about that here: https://github.com/exoframejs/exoframe/issues/153

As a workaround you can deploy using docker-compose file that uses your pre-built image - that should work 🤔

**Comment by mradke** [comment]
Ok I will try this over the weekend. That sounds like a reasonable plan 👍 
Thanks for taking the time 😊

**Comment by mradke** [comment]
Well I managed to build a custom image but a bunch of other questions arise from this.

1) Can exoframe deploy an image that is only present on the local machine?
2) How does exoframe decide if it should use the `docker-compose` or `Dockerfile` deployment method?
3) Is my understanding correct that I can configure multiple traefik urls, by specifying labels under each service that shall have its own url?

E. g.
```
services:
  frontend:
    image: "frontend:latest"
    labels:
      traefik.frontend.rule: "Host:frontend.example.com"
      traefik.port: "3000"
  api:
    image: "api:latest"
    labels:
      traefik.frontend.rule: "Host:api.example.com"
      traefik.port: "4000"
```

---
For reference, or anyone looking into this: I am trying to deploy an elixir application. I followed https://hexdocs.pm/distillery/guides/working_with_docker.html for the most part to build a custom image that contains only the release tarball that we want to run in our docker container.
