### ISSUE TITLE
HTTPS not working when prefixed with www?

### ISSUE THREAD

**Issue by maxime1992** [exoframejs/exoframe#209]
Hi,

I'm deploying my frontend using a docker-compose file which looks like the following:
```
version: '3'
services:
  frontend:
    image: ...
    labels:
      traefik.frontend.rule: 'Host:albiecorace.com'
      traefik.port: 80
    expose:
      - '80'
```

Now, if you access `https://albiecorace.com` it's fine. But if you access `https://www.albiecorace.com` it says that the certificate cannot be trusted. Taking a look on the certificate, the first one looks like that:

![image](https://user-images.githubusercontent.com/4950209/52554991-63b15100-2de0-11e9-9160-78e7cc7f93c0.png)

But the one with `www` is invalid:

![image](https://user-images.githubusercontent.com/4950209/52555033-82afe300-2de0-11e9-974c-607223d6c395.png)

And... Is coming from traefik :thinking: 
![image](https://user-images.githubusercontent.com/4950209/52555056-8fccd200-2de0-11e9-9d61-527106218e9a.png)

Not sure what I'm missing here. I've been looking into:
- https://github.com/exoframejs/exoframe/issues/106
- https://github.com/exoframejs/exoframe/issues/198
- https://docs.traefik.io/basics/#entrypoints
- https://github.com/containous/traefik/issues/2829
- https://stackoverflow.com/questions/53356384/traefik-not-trusting-ssl-certificate

But no luck. I'm probably missing something here...

Any help would be highly appreciated.

Thanks

**Comment by yamalight** [comment]
@maxime1992 traefik will actually redirect you to `https` when you try to access `http`. I just tried opening the domain you've listed on `http` and it works correctly and redirects to https for me in Chrome 🤔

**Comment by maxime1992** [comment]
@yamalight sorry I meant https://www.albiecorace.com :zipper_mouth_face: (not http in that case)

**Comment by yamalight** [comment]
@maxime1992 that address gives 404 if you ignore the certificate error - that's exactly why that's an error - there's no content there 😃

**Comment by maxime1992** [comment]
:sweat_smile: ha that starts to make sense. But should I just have another conf into my docker-compose like that:
```
  redirect:
    image: ...
    labels:
      traefik.redirect.rule: 'Host:www.albiecorace.com'
      traefik.port: 80
    expose:
      - '80'
```

Which just redirects to the good one? :thinking: Feels weird...
