### ISSUE TITLE
[Question] How to use the new possibilities in v.4

### ISSUE THREAD

**Issue by mradke** [exoframejs/exoframe#214]
Super impressed with the speed of development here, you're doing really a great job 👍 

So now that we have the shiny new option of providing a tar file to deploy that how do we actually use it from a docker-compose file?

E. g. I'm using `docker save api:latest > api_latest.tar` and exoframe is uploading everything as supposed after providing `"imageFile": "api_latest.tar"` 🎉 

But how do we use it inside the docker-compose file that I'd like to use:

```
version: "3"
services:
  db:
    image: "postgres:10.6-alpine"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
  app:
    image: "api:latest" <-- What to specify here, to use the uploaded tar file?
    ports:
      - "4000:4000"
    labels:
      traefik.frontend.rule: "Host:api.example.com"
      traefik.port: "4000"
    depends_on:
      - db
```
