### ISSUE TITLE
ACME certificate for domains

### ISSUE THREAD

**Issue by FDiskas** [exoframejs/exoframe#224]
If I enable SSL in docker logs I see allot requests to letsencrypt
This could lead my server to get banned from their services.
Suggestion to prevent this:
1. check if url is valid
1. check if url is accessable
```
time="2019-03-31T18:59:29Z" level=error msg="Unable to obtain ACME certificate for domains \"mongo.exo-root-demo-server\" detected thanks to rule \"Host:mongo.exo-root-demo-server\" : unable to generate a certificate for the domains [mongo.exo-root-demo-server]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:malformed :: Error creating new order :: Name does not end in a public suffix, url: "
time="2019-03-31T18:59:29Z" level=error msg="Unable to obtain ACME certificate for domains \"mongo-express.exo-root-demo-server\" detected thanks to rule \"Host:mongo-express.exo-root-demo-server\" : unable to generate a certificate for the domains [mongo-express.exo-root-demo-server]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:malformed :: Error creating new order :: Name does not end in a public suffix, url: "
time="2019-03-31T19:00:55Z" level=error msg="Unable to obtain ACME certificate for domains \"mongo.exo-root-demo-server\" detected thanks to rule \"Host:mongo.exo-root-demo-server\" : unable to generate a certificate for the domains [mongo.exo-root-demo-server]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:malformed :: Error creating new order :: Name does not end in a public suffix, url: "
```

**Comment by yamalight** [comment]
Letsencrypt only issues SSL certificates for public domains. If you are not exposing something publicly - you can't get a cert for it.

**Comment by FDiskas** [comment]
I can see invalid urls in logs also thats not good

**Comment by yamalight** [comment]
If they appear in logs - you must've assigned them somewhere. Exoframe does not manually set any domains

**Comment by FDiskas** [comment]
nope. I'm using just docker-compose file
```
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: demo-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongoData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: hapidb

  mongo-express:
    image: mongo-express
    container_name: demo-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  api:
    image: strapi/strapi
    container_name: demo-strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=hapidb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=example
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=admin
      - HOST=mongo
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - 1337:${PORT}
    volumes:
      - strapiAppFiles:/usr/src/api/strapi-app
      - ./config:/usr/src/api/strapi-app/config
    labels:
      traefik.frontend.rule: 'Host:api.rank.lt'
      traefik.port: ${PORT}
    depends_on:
      - mongo
volumes:
  strapiAppFiles:
  mongoData:
```
