### ISSUE TITLE
Can't deploy to swarm

### ISSUE THREAD

**Issue by alexisromagnoli** [exoframejs/exoframe#230]
I've created a docker swarm on my desktop machine, with only one node, to test a deploy of  https://github.com/exoframejs/node-cd-demo project.

I got this error 

The exoframe command output is:

```
Deploying current project to endpoint: http://exoframe.local

No .exoframeignore file found, using default ignores

Ignoring following paths: [ '.git', 'node_modules', '.exoframeignore' ]
[info] Deploying docker-compose project..
[verbose] Compose file modified
[info] Some services (exoframe-server, traefik) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
[info] traefik uses an image, skipping
[info] exoframe-server uses an image, skipping
[info] Docker-compose exited with code 0
[verbose] Compose file modified for stack deploy
Error deploying project: Error: Something went wrong!
Build log:

No log available

Original error: { Error: Something went wrong!
    at Object.exports.handler (/usr/lib/node_modules/exoframe/src/commands/deploy.js:200:19)
    at process._tickCallback (internal/process/next_tick.js:68:7) response: {} }
Original response: {}
```

After doing all exoframe configuration I ran the commands below:

```
$ docker stack deploy -c docker-compose.yml exoframe
$ exoframe -vvv
```

I can access exoframe.local and to traefik.local through a browser.

But the app as I said is not deployed after running exoframe -vvv command the exoframe/server container gets restarted.

I'm using this docker-compose.yml file to run the swarm:
```
version: '3'

services:
  exoframe-server:
    image: exoframe/server
    deploy:
      labels: 
      - "traefik.enable=true"
      - "traefik.backend=exoframe-server"
      - "traefik.frontend.rule=Host:exoframe.local"
      - "traefik.port=8080"
      - "traefik.docker.network=mystack_traefik-net"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
    - /home/user/.exoframe:/root/.exoframe 
    - /home/user/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro 
    environment: 
    - EXO_PRIVATE_KEY=your_private_key 
    networks: 
    - internal-network

  traefik:
    image: traefik:1.7
    ports:
      - "80:80"
      - "8080:8080"
    command: --web \
      --docker \
      --docker.swarmMode \
      --docker.endpoint=unix:///var/run/docker.sock \
      --docker.domain=traefik.local \
      --docker.watch \
      --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]
      labels:
        - traefik.frontend.rule=Host:traefik.local
        - traefik.enable=true
        - traefik.port=8080
        - traefik.frontend.entryPoints=http
    networks:
      - internal-network

networks: 
  internal-network:
    external: true
```

I've created the swarm network using this:
```
docker network create --scope swarm --driver overlay --attachable internal-network
```

This is the content of my /etc/hosts file:
```
127.0.0.1	exoframe.local
127.0.0.1	exoframe.demo
127.0.0.1	traefik.local
```

This is my .exoframe/server.config.yml
```
# whether debug mode is enabled, default "false"
debug: true 

# whether to enable letsencrypt, default "false"
letsencrypt: false

# email used for letsencrypt
letsencryptEmail: your@email.com

# whether to apply gzip compression, default "true"
compress: true

# base top-level domain to use for deployments without domains specified, default "false"
# used as postfix, e.g. if you specify ".example.com" (dot is auto-prepended if not present)
# all your deployments will be autodeployed as "deployment-id.example.com"
baseDomain: false

# CORS support; can be "true" ("*" header) or object with "origin" property, default "false"
cors: false

# Traefik image to be used; set to "false" to disable traefik management, default "traefik:latest"
traefikImage: false

# Traefik container name, default "exoframe-traefik"
traefikName: 'exoframe-traefik'

# Additional Traefik start args, default []
traefikArgs: []

# Network used by traefik to connect services to, default "exoframe"
exoframeNetwork: 'exoframe'

# server image update channel; can be "stable" or "nightly", default "stable"
updateChannel: 'stable'

# path to folder with authorized_keys, default "~/.ssh"
publicKeysPath: '/root/.ssh'

# whether Exoframe server whould be running in swarm mode, default "false"
swarm: true

# plugins config
plugins:
  # list of plugins that has to be installed and loaded by exoframe-server on startup
  install: ['exoframe-plugin-swarm']
  # specific plugin config (see plugins docs to know what property they use)
  swarm:
    enabled: true
```

Project exoframe.json file:
```
{
  "name": "demo",
  "restart": "on-failure:2",
  "domain": "exoframe.demo",
  "project": "demo",
  "hostname": "exoframe.demo"
}

```

Any help will be highly appreciated. :-)

**Comment by yamalight** [comment]
According to log you are deploying docker-compose project. Have you modified node-cd-demo in any way?

**Comment by alexisromagnoli** [comment]
Nop

**Comment by alexisromagnoli** [comment]
Sorry, my mistake, you're right I just realized I added the docker-compose.yml file described above to the root folder of the project. 
So I've created in the root folder a .exoframeignore file with this content:
docker-compose.yml
That solved the deploy problem. 
It would be nice to add this as an example to the documentation to avoid this pitfalls, among with a clear error message. :-)

Now I can't connect to the container going to: exoframe.demo, it apparently is caused because the label: 
```
traefik.frontend.rule=Host:exoframe.demo
```
hasn't been added to the container. I'll take a look into this later.

Thanks a lot for your help!!

**Comment by yamalight** [comment]
When running in swarm mode - labels are added to services, not to containers, so this is expected.
Does `exoframe.demo` resolves to the IP of your swarm master node?

**Comment by alexisromagnoli** [comment]
Yes, exoframe.demo resolves to the same ip as the swarm master node, which is 127.0.0.1, because I'm running the swarm on my local machine.
I've changed the network of the exoframe-server and traefik services to "exoframe-swarm" in the docke-compose-yml file and now I can connect to exoframe.demo and the updates of the deploy works fine when I run exoframe -u.
Is there anyway to change the network of the deployed container to "internal-web" instead of "exoframe-swarm" for example?.

Thx!.

**Comment by yamalight** [comment]
You can tell exoframe server to use custom network using [server config](https://github.com/exoframejs/exoframe/blob/master/docs/ServerConfiguration.md)

**Comment by alexisromagnoli** [comment]
I've tried changing the server.config.yml file doing the changes below with no luck:
```
exoframeNetwork: 'internal-web'
```
also: 
```
plugins:
  # list of plugins that has to be installed and loaded by exoframe-server on startup
  install: ['exoframe-plugin-swarm']
  # specific plugin config (see plugins docs to know what property they use)
  swarm:
    enabled: true
    userNetwork: 'internal-web'
```
The container network stills the same: exoframe-swarm

**Comment by yamalight** [comment]
Config seems fine. Have you re-deployed the app after changing the config?

**Comment by alexisromagnoli** [comment]
Yes, and I've tried erasing the containers, too.

Which one is the param I should change in the config.?
This one:
```
exoframeNetwork: 'internal-web'
```
or 
```
plugins:
  # list of plugins that has to be installed and loaded by exoframe-server on startup
  install: ['exoframe-plugin-swarm']
  # specific plugin config (see plugins docs to know what property they use)
  swarm:
    enabled: true
    userNetwork: 'internal-web'
```
I've been reading the code of the exoframe-plugin-swarm, but I can't find the problem.

Doing the deploy with this server.config.yml config:
```
# whether debug mode is enabled, default "false"
debug: true

# whether to enable letsencrypt, default "false"
letsencrypt: false

# email used for letsencrypt
letsencryptEmail: your@email.com

# whether to apply gzip compression, default "true"
compress: true

# base top-level domain to use for deployments without domains specified, default "false"
# used as postfix, e.g. if you specify ".example.com" (dot is auto-prepended if not present)
# all your deployments will be autodeployed as "deployment-id.example.com"
baseDomain: false

# CORS support; can be "true" ("*" header) or object with "origin" property, default "false"
cors: false

# Traefik image to be used; set to "false" to disable traefik management, default "traefik:latest"
traefikImage: false

# Traefik container name, default "exoframe-traefik"
traefikName: 'exoframe'

# Additional Traefik start args, default []
traefikArgs: ['']

# Network used by traefik to connect services to, default "exoframe"
#exoframeNetwork: 'exoframe'
exoframeNetwork: 'internal-web'

# server image update channel; can be "stable" or "nightly", default "stable"
updateChannel: 'stable'

# path to folder with authorized_keys, default "~/.ssh"
publicKeysPath: '/root/.ssh'

# whether Exoframe server whould be running in swarm mode, default "false"
swarm: true

# plugins config
plugins:
  # list of plugins that has to be installed and loaded by exoframe-server on startup
  install: ['exoframe-plugin-swarm']
  # specific plugin config (see plugins docs to know what property they use)
  swarm:
    enabled: true
    userNetwork: 'internal-web'
```

Inspecting the container:
```
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "fbc4aec48beb32ce8c8fdb50956ac3600ecbe39bed2593ad9256ba3fd7afcd62",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/fbc4aec48beb",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "exoframe-swarm": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.3.50"
                    },
                    "Links": null,
                    "Aliases": [
                        "48943db787cc"
                    ],
                    "NetworkID": "1qabjsi3ucgyinmlz0mnb8j7a",
                    "EndpointID": "a2006a14a1f81d80c6c4173e796a40b636fdb24fb68bd71863707500f52a0f4e",
                    "Gateway": "",
                    "IPAddress": "10.0.3.50",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:03:32",
                    "DriverOpts": null
                }
            }
        }
```

Inspecting the demo app service
```
[
    {
        "ID": "yfhulz5x5b94fqpi7k9ciw6uy",
        "Version": {
            "Index": 379655
        },
        "CreatedAt": "2019-04-15T12:41:04.858835198Z",
        "UpdatedAt": "2019-04-15T12:41:04.918193154Z",
        "Spec": {
            "Name": "exo-admin-demo-bbd55fd0",
            "Labels": {
                "exoframe.deployment": "exo-admin-demo-bbd55fd0",
                "exoframe.project": "demo",
                "exoframe.user": "admin",
                "traefik.backend": "exoframe.demo",
                "traefik.docker.network": "exoframe-swarm",
                "traefik.enable": "true",
                "traefik.frontend.rule": "Host:exoframe.demo",
                "traefik.port": "80"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "exo-admin-demo:latest",
                    "Env": [
                        "EXOFRAME_DEPLOYMENT=exo-admin-demo-bbd55fd0",
                        "EXOFRAME_USER=admin",
                        "EXOFRAME_PROJECT=demo",
                        "EXOFRAME_HOST=exoframe.demo"
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Isolation": "default"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "Delay": 5000000000,
                    "MaxAttempts": 1
                },
                "Placement": {},
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 2,
                "Delay": 10000000000,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "start-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "Networks": [
                {
                    "Target": "1qabjsi3ucgyinmlz0mnb8j7a",
                    "Aliases": [
                        "exoframe.demo"
                    ]
                }
            ]
        },
        "Endpoint": {
            "Spec": {},
            "VirtualIPs": [
                {
                    "NetworkID": "1qabjsi3ucgyinmlz0mnb8j7a",
                    "Addr": "10.0.3.49/24"
                }
            ]
        }
    }
]
