### ISSUE TITLE
Usage from within a CI/CD (Gitlab) environment and Review Apps

### ISSUE THREAD

**Issue by SeaLife** [exoframejs/exoframe#243]
So i got a basic idea of how we could use this in e.g. Gitlab to deploy our applications..

I would like to provide a custom exoframe.json file for deploying from develop branch and from any tag...

So, if i create a tag, the CI should run something like `exoframe deploy -u -f exoframe-production.json`
And on any other branch, just `exoframe deploy` (which should just use the default filename).

There sould also be file containing the destination url, so you can utilize this, to set the environment url in Gitlab to provide a button to access the app.

There should also be a file containing the deployment ID to undeploy the app from within the gitlab ci context (a manual job for example).
(this could be a json file including the information above)...

See https://about.gitlab.com/2017/07/11/dockerizing-review-apps/

Regards
SeaLife

**Comment by yamalight** [comment]
Hey @SeaLife!
There's already a ticket for alternate config support (https://github.com/exoframejs/exoframe/issues/215) and for non-interactive config edits as well (https://github.com/exoframejs/exoframe/issues/218).

I'm not sure I get the idea of a file with deployment ID - when would you want to remove deployments in CI? (besides from updating current deployments, which is already supported)

**Comment by SeaLife** [comment]
So, in Gitlab you can deploy apps and set them (a URL) as "Review App"...
Another people can go to the website (which is generated) and take a look on the actual deployed app.
But after the review, the "Review App" is not needed anymore and can be undeployed. (Which is done by a manual CI step in Gitlab).

The File can be used for simple extraction of the currently made deployment. So Gitlab know which instance it has to undeploy exactly. The URL information to tell Gitlab were the "Review App" is deployed. :)

**Comment by SeaLife** [comment]
Oh, #215 got even the same requirements i got, did not see the issue, sorry.

The #218 i dont get that right... I can indeed run

```
exoframe endpoint <url>
exoframe deploy -u -t <token>
```

in a non-interactive environment? A `exoframe config` does not work, but its not needed in a CI environment?

Regards

**Comment by yamalight** [comment]
I see. Exoframe does output the deployment ID upon success, so if you want a file with it - you could just use something like `grep` or `awk` to grab it, e.g.: `exo -u | awk 'END{ print $1 }' > id.txt`

**Comment by SeaLife** [comment]
This would probably end up not very well....
I need the URL too.. :(

**Comment by yamalight** [comment]
#218 is about modifying config in non-interactive manner. E.g. being able to say `exoframe config --domain=test.domain.com`

**Comment by yamalight** [comment]
@SeaLife URL is also returned upon successful deployment, you can also use e.g. `awk` to grab it

**Comment by SeaLife** [comment]
Mhhh... `awk` does not seems to be the right tool using in a ci job... It feels more like a workaround..

**Comment by SeaLife** [comment]
Ouh, `exoframe rm` does not allow a token to be used....

**Comment by yamalight** [comment]
@SeaLife it currently doesn't yep. I've opened an issue for it (#244) and would happily accept a PR that adds it

**Comment by SeaLife** [comment]
Okay, i've run into several issues now.. :D 

The ID, is it always the generated one ?

Thanks for opening an issue for this. :)

**Comment by yamalight** [comment]
ID will always be a new unique generate one, yes

**Comment by SeaLife** [comment]
Okay...

So this is the Workflow using Gitlab CI and Review Apps


- Starting from the `node:latest` image (cause there is no official exoframe client image?)
- Installing exoframe `npm install -g exoframe`
- Setting the exoframe endpoint `exoframe endpoint $EXOFRAME_SERVER`

So far so good, after this, the complicated stuff is about to start:
I need to start the app with a specific name and url set by e.g. the git commit. (which includes #218) 

If this works, i can create a job in Gitlab CI doing like this:

```yml
review:
  stage: review
  image: node:latest
  script:
  - "npm install exoframe -g"
  - "exoframe endpoint $EXOFRAME_SERVER"
  - "exoframe config --domain \"${CI_COMMIT_REF_NAME}.example.tld\" --name \"${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}\"
  - "exoframe -u -t $EXOFRAME_TOKEN"
  environment:
    name: review-${CI_COMMIT_REF_NAME}
    url: "${CI_COMMIT_REF_NAME}.example.tld"

undeploy_review:
  stage: review
  image: node:latest
  script:
  - "npm install exoframe -g"
  - "exoframe endpoint $EXOFRAME_SERVER"
  - "exoframe rm review-${CI_COMMIT_REF_NAME} -t $EXOFRAME_TOKEN"
  when: manual
  environment:
    name: review-${CI_COMMIT_REF_NAME}
    action: stop
```

If this does not work (setting a specific name), i need a function to undeploy by url...
The problem is, i cant access any vars or anything like this generated in the build step which creates the review app.

```yml
undeploy_review:
  stage: review
  image: node:latest
  script:
  - "npm install exoframe -g"
  - "exoframe endpoint $EXOFRAME_SERVER"
  - "exoframe rm --url ${CI_COMMIT_REF_NAME}.example.tld -t $EXOFRAME_TOKEN"
  when: manual
  environment:
    name: review-${CI_COMMIT_REF_NAME}
    action: stop
```
