### ISSUE TITLE
Github Action for Exoframe

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#260]
Github actions are releasing soon-ish.
Having a prepared github action for exoframe would be neat.
The easiest way to go about it would be to fork [heroku](https://github.com/actions/heroku) (see also [npm](https://github.com/actions/npm), [npx](https://github.com/mikeal/npx)) action and tweak it accordingly.
Something like this should work:
```
workflow "Deploy" {
  on = "push"
  resolves = ["deploy"]
}

action "deploy" {
  uses = "exoframe/action@master"
  args = "deploy -e http://exo.server.com -t $EXO_TOKEN"
  secrets = ["EXO_TOKEN"]
}
```

**Comment by yamalight** [comment]
No longer sure the action is needed. This seems to work pretty well:
```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install
        run: yarn install
      - name: deploy
        run: npx exoframe -u -e https://exoframe.example.net -t $EXO_TOKEN
        env:
          EXO_TOKEN: ${{ secrets.EXO_TOKEN }}
```

Maybe just documenting this would be enough 🤔
