### ISSUE TITLE
Migrate from Travis-CI to Github Actions

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#283]
Initial work for server has been done in https://github.com/exoframejs/exoframe-server/pull/33 (huge thanks to @anbraten).

Things to do:
- [x] Replace badges in readme
- [x] Add coveralls to all server tests
- [x] Auto-bump `fix` version in npm before publishing from `develop`
- [x] Migrate CLI to github actions

**Comment by anbraten** [comment]
Github actions seems to work quite well with a monorepo:
```
on:
  push:
    branch: develop
    paths:
      - 'packages/cli/**'
```

As the issues and documentation are already inside this main repo, I think adding the server and maybe later the other packages sounds quite handy to me.
