### ISSUE TITLE
RequestError: unable to verify the first certificate

### ISSUE THREAD

**Issue by niklasgrewe** [exoframejs/exoframe#287]
Hi, i have reinstalled exoframe with traefik on my Debian 10 server. So I deleted the `exoframe-server` and `exoframe-traefik` container and also deleted the `.exoframe` directory except for the `server.config.yml` file. Afterwards I could access my website (which I already deployed) as usual via my domain. 

My problem now is that I can't log in via the CLI. I get the following error: 

```
Error logging in! Error getting login request phrase. Make sure your endpoint is correct! RequestError: unable to verify the first certificate
```

When I enter my exoframe endpoint url in the browser, I see the standard exoframe website with the logo via HTTP. When I access the site via HTTPS, I get a `404 NOT FOUND ERROR`
When I then check the certificate in the browser, I notice that Traefik uses the standard certificate. 

<img width="506" alt="Bildschirmfoto 2020-03-30 um 16 44 07" src="https://user-images.githubusercontent.com/61348836/77925880-b4666080-72a5-11ea-96ae-e69a21dd0a9d.png">

How can I fix this?

**Comment by yamalight** [comment]
Please refer to [Installation and usage with Letsencrypt](https://github.com/exoframejs/exoframe/blob/master/docs/ServerInstallation.md#installation-and-usage-with-letsencrypt) part of server docs and see if that helps.

**Comment by niklasgrewe** [comment]
@yamalight thanks for the reference. I have actually used the wrong configuration 🙈But now I have a different error message when I try to login with `exoframe login`

```
Error logging in! Check your username and password and try again. HTTPError: Response code 405 (Method Not Allowed)
```
I already had the same error during my first installation. Unfortunately I don't remember how I fixed it. I have used this config to create `exoframe-server` docker container:

```yaml
docker run -d \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /path/to/exoframe-folder:/root/.exoframe \
  -v /home/user/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \
  -e EXO_PRIVATE_KEY=your_private_key \
  --label traefik.enable=true \
  --label "traefik.http.routers.exoframe-server.rule=Host(\`exoframe.your-host.com\`)" \
  --label "traefik.http.routers.exoframe-server-web.rule=Host(\`exoframe.your-host.com\`)" \
  --label traefik.http.routers.exoframe-server.tls.certresolver=exoframeChallenge \
  --label traefik.http.middlewares.exoframe-server-redirect.redirectscheme.scheme=https \
  --label traefik.http.routers.exoframe-server-web.entrypoints=web \
  --label traefik.http.routers.exoframe-server-web.middlewares=exoframe-server-redirect@docker \
  --label traefik.http.routers.exoframe-server.entrypoints=websecure \
  --label entryPoints.web.address=:80 \
  --label entryPoints.websecure.address=:443 \
  --restart always \
  --name exoframe-server \
  exoframe/server
```
I have of course replaced this line
```
-v /home/user/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \
```
with my username


and then I tested the config with this line:
```
-v $HOME/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \
```
i'm pretty sure i fixed the bug somehow by changing this line, but it didn't work that way

my `server.config.yml` looks like this

```yaml
# whether to enable letsencrypt, default "false"
letsencrypt: true

# email used for letsencrypt
letsencryptEmail: niklas@grewe.io

# whether to apply gzip compression, default "true"
compress: true

# base top-level domain to use for deployments without domains specified, default "false"
# used as postfix, e.g. if you specify ".example.com" (dot is auto-prepended if not present)
# all your deployments will be autodeployed as "deployment-id.example.com"
baseDomain: false

# CORS support; can be "true" ("*" header) or object with "origin" property, default "false"
cors: false

# Traefik image to be used; set to "false" to disable traefik management, default "traefik:latest"
traefikImage: 'traefik:latest'

# Traefik container name, default "exoframe-traefik"
traefikName: 'exoframe-traefik'

# Additional Traefik start args, default []
traefikArgs: []

# Network used by traefik to connect services to, default "exoframe"
exoframeNetwork: 'exoframe'

# server image update channel; can be "stable" or "nightly", default "stable"
updateChannel: 'stable'

# path to folder with authorized_keys, default "~/.ssh"
publicKeysPath: '/home/user/.ssh'

# whether Exoframe server would be running in swarm mode, default "false"
swarm: false

# plugins config
# plugins:
  # list of plugins that has to be installed and loaded by exoframe-server on startup
  # install: ['exoframe-plugin-swarm']
  # specific plugin config (see plugins docs to know what property they use)
  # swarm:
    # enabled: true
```
