### ISSUE TITLE
Trouble to run services without exoframe but with traefik

### ISSUE THREAD

**Issue by niklasgrewe** [exoframejs/exoframe#304]
Hi, i want to run a rocketchat instance on my exoframe server using traefik. I am using a `docker-compose` file looks like this:

```yaml
version: '3'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://chat.grewe.io
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.mail.com
#       - HTTP_PROXY=http://proxy.domain.com
#       - HTTPS_PROXY=http://proxy.domain.com
    depends_on:
      - mongo
    ports:
      - 3000:3000
    labels:
       - "traefik.enable=true"
       - "traefik.http.middlewares.rocketchat-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.rocketchat-web.entrypoints=web"
       - "traefik.http.routers.rocketchat-web.middlewares=directus-redirect@docker"
       - "traefik.http.routers.rocketchat-web.rule=Host(`my.domain.com`)"
       - "traefik.http.routers.rocketchat.entrypoints=websecure"
       - "traefik.http.routers.rocketchat.rule=Host(`my.domain.com`)"
       - "traefik.http.routers.rocketchat.tls.certresolver=exoframeChallenge"
       - "traefik.http.services.rocketchat.loadbalancer.server.port=3000"

  mongo:
    image: mongo:4.0
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
      - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo
```
When i try to access the rocketchat instance i get the following results:
```
http://my.domain.com   -> 404 Not Found
https://my.domain.com  -> Gateway Timeout but valid HTTPS Connection with generated Let's Encrypt Certificate
```
So where is my issue? Do i need to use the `exoframe` docker network to get this working correctly? Hope everyone can help me to fix that

**Comment by yamalight** [comment]
Are you deploying your compose using exoframe cli? If not - then yes, you do need to manually add all your containers to exoframe network.

Your redirect middleware also doesn't look right (unless that's something you've defined in traefik config):

> "traefik.http.routers.rocketchat-web.middlewares=directus-redirect@docker"

**Comment by niklasgrewe** [comment]
@yamalight thanks for quick answer. Perfect it works now. But why i need to add the exoframe network to all containers?

**Comment by yamalight** [comment]
Don't have to add all of them - just the ones that traefik should pick up (since it monitors that network specifically).
If you want to - you can use different network for db, etc. But it does complicate the overall setup then.

**Comment by niklasgrewe** [comment]
ok thanks for the explanation. Now everything works as expected.

**Comment by niklasgrewe** [comment]
@yamalight sorry for my reply, but now I can't get my keycloak server to run. I have set exactly the same labels as in my rocket chat, but this time it does not work. I get the message again from Traefik: `404 Not found` My `docker-compose.yml` file looks like this:

```yaml
version: "3.4"

services:
  keycloak_db:
    image: postgres:11.2-alpine
    restart: unless-stopped
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=dbpassword
        - POSTGRES_ROOT_PASSWORD=myrootpassword
    networks:
        - exoframe
    volumes:
        - ./data/db:/var/lib/postgresql/data
    labels:
        - "traefik.enable=false"

  keycloak:
    image: jboss/keycloak:latest
    hostname: keycloak
    restart: unless-stopped
    volumes:
        - ./data/themes:/opt/jboss/keycloak/themes
    environment:
        - DB_VENDOR=POSTGRES
        - DB_ADDR=keycloak_db
        - DB_DATABASE=keycloak
        - DB_PORT=5432
        - DB_USER=dbuser
        - DB_SCHEMA=public
        - DB_PASSWORD=dbpassword
        - PROXY_ADDRESS_FORWARDING=true
        - KEYCLOAK_LOGLEVEL=INFO
        - KEYCLOAK_USER=user
        - KEYCLOAK_PASSWORD=password
    ports:
        - 8080:8080
    networks:
        - exoframe
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=exoframe"
        - "traefik.http.middlewares.keycloak-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.keycloak-web.entrypoints=web"
        - "traefik.http.routers.keycloak-web.middlewares=keycloak-redirect@docker"
        - "traefik.http.routers.keycloak-web.rule=Host(`sub.domain.com`)"
        - "traefik.http.routers.keycloak.entrypoints=websecure"
        - "traefik.http.routers.keycloak.rule=Host(`sub.domain.com`)"
        - "traefik.http.routers.keycloak.tls.certresolver=exoframeChallenge"
        - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]


networks:
  exoframe:
    external: true
```
I also took a look at this [docker-compose.yml](https://github.com/ibuetler/docker-keycloak-traefik-workshop/blob/master/keycloak/docker-compose.yml) file where traefik is also used. I'm surprised that no port was exposed in the config and it seems to work anyway. 

Do you have an idea where the error might be?
